# Site settings
author: Alan Krajina
title: On My Block
header-img: img/home-bg.png
email: alankrajina88@gmail.com
copyright_name: Alan Krajina
description: > # this means to ignore newlines until "baseurl:"
  Tell me and I forget. Teach me and I remember. Involve me and I learn.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AlanKrajina

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
